#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: build-nightly

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
       path: ~/.m2/repository
       key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
       restore-keys: |
        ${{ runner.os }}-maven-      
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Login to docker.io
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        registry: docker.io
    - name: Login to quay.io
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
        registry: quay.io
    - name: Build with Maven
      run: mvn -B clean install -U -Pintegration
    - name: Build docker images
      run: |
        cd dockerfiles
        ./build.sh 
        cd ..
    - name: Push docker images
      run: |
        docker push quay.io/eclipse/endpoint-watcher:nightly
        docker push quay.io/eclipse/che-endpoint-watcher:nightly
        docker push quay.io/eclipse/che-keycloak:nightly
        docker push quay.io/eclipse/che-postgres:nightly
        docker push quay.io/eclipse/che-dev:nightly
        docker push quay.io/eclipse/che-server:nightly
        docker push quay.io/eclipse/che-dashboard-dev:nightly
        docker push quay.io/eclipse/che-e2e:nightly
    - name: Build ubi8 Che Server image
      run: 
        ./dockerfiles/che/build.sh --dockerfile:"rhel.Dockerfile" --tag:"rhel-nightly"
    - name: Push ubi8 Che Server image
      run: 
        docker push quay.io/eclipse/che-server:rhel-nightly